name: "streamlit CD action"
on:
  push:
    branches:
      - 'khs/action'
      
jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - name: print variable
        run: echo ${{ github.event.repository.name }}
